### ISSUE TITLE
Reduce indirections?

### ISSUE THREAD

**Issue by taktoa** [andrewthad/prim-ref#1]
In the [definition](https://github.com/andrewthad/prim-ref/blob/402ac08e6a0bcd6896e764c0b3902745b6145833/src/Data/Primitive/PrimRef.hs#L49) of PrimRef, you/Kmett define it as:

```
newtype PrimRef s a = PrimRef (MutableByteArray s)
```

It seems to me that in most cases, since MutableByteArray [is boxed](https://hackage.haskell.org/package/primitive-0.6.3.0/docs/src/Data-Primitive-ByteArray.html#MutableByteArray) and doesn't have an `{-# UNPACK #-}` pragma, this will have fewer indirections:

```
data PrimRef s a = PrimRef {-# UNPACK #-} (MutableByteArray# s)
```

**Comment by taktoa** [comment]
Though I'm not sure if you're allowed to put an `{-# UNPACK #-}` pragma on a constructor field with an unboxed type. I guess maybe this requires newtypes over `#`, which are not yet in GHC.

**Comment by taktoa** [comment]
Nevermind, this doesn't make sense.

**Comment by chessai** [comment]
data PrimRef s a = PrimRef {-# UNPACK #-} !(MutableByteArray# s) ?
(bangpatterns)

**Comment by taktoa** [comment]
```
{-# LANGUAGE MagicHash #-}

module Main where

import GHC.Prim (Int#)

data Foo = Foo {-# UNPACK #-} !Int#
```

and

```
[1 of 1] Compiling Temp             ( Temp.hs, Temp.o )

Temp.hs:7:12: warning:
    • Ignoring unusable UNPACK pragma on the first argument of ‘Foo’
    • In the definition of data constructor ‘Foo’
      In the data type declaration for ‘Foo’
```

**Comment by chessai** [comment]
ghc has forsaken us

**Comment by andrewthad** [comment]
For the benefit of future readers who stumble upon this issue, I'll point out that `newtype` doesn't support unpacking. Also, `newtype`s don't get in the way of unpacking. So, we can write this:

    newtype Foo = Foo Int
    newtype Bar = Bar Foo
    newtype Baz = Baz Bar
    
    data Thing = Thing Bool {-# UNPACK #-} !Baz

And GHC will turn the data constructor for `Thing` into:

    data Thing = Thing Bool Int#

**Comment by taktoa** [comment]
Of course, `newtype`s are automatically unpacked; my issue was just with `MutableByteArray`, which is not a newtype, not strict, and has no `{-# UNPACK #-}` pragma. Unfortunately, since my proposed version of `PrimRef` is lifted, GHC cannot unpack it because then you'd have an unboxed lifted value (which makes no sense). Hence, we actually need `newtype`s over `#`.

**Comment by andrewthad** [comment]
> Hence, we actually need `newtype`s over `#`.

[I agree wholeheartedly](https://github.com/ghc-proposals/ghc-proposals/blob/1b34f1114a1bc5bf6b0e3492318a0266d80283c4/proposals/0013-unlifted-newtypes.rst).

But I don't agree with the reason you cite here. Unlifted newtypes offer no benefit at all over the status quo. I assume that you are doing something like:

```
data Stack s a = Stack
  {-# UNPACK #-} !(PrimRef s Int)
  {-# UNPACK #-} !(PrimRef s Int) 
  {-# UNPACK #-} !(Payload s a)
```

Where payload is the actual meat of the stack (irrelevant to this discussion). Even with unlifted newtypes, if you could write:

```
newtype PrimRef# s a = PrimRef# (MutableByteArray# s)
data Stack s a = Stack
  (PrimRef# s Int)
  (PrimRef# s Int) 
  {-# UNPACK #-} !(Payload s a)
```

You would get the same generated GHC core and consequently the same performance.
